---
apiVersion: v1
kind: Service
metadata:
  namespace: prototype
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prototype
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      namespace: prototype
      labels:
        app: backend
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "true"
    spec:
      containers:
        - name: backend
          image: parameshg/zerotrust-prototype-backend-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: "0.5Gi"
              cpu: "0.5"
        - name: debug
          image: nicolaka/netshoot:latest
          imagePullPolicy: IfNotPresent
          command: ["bash"]